language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r handysub * # 현재 위치의 모든 파일을 해당이름으로 압축
  - mkdir -p deploy
  - mv handysub.zip deploy/handysub.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: handysub-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      all_branches: true # master말고 다른 모든 브런치 허용


  # CodeDeploy 배포
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repos settings에 설정된 값
    bucket: handysub-springboot-build # s3 버킷
    key: handysub.zip # 빌드 파일 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: handySub # 웹 콘솔에서 등록한 CodeDelpoy 애플리케이션 이름
    deployment_group: handySub-group # 웹 콘솔에서 등록한 CodeDelpoy 배포 그룹 이름
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true # master말고 다른 모든 브런치 허용

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - syt07100@gmail.com
