spring:
  data:
    mongodb:
      authentication-database: admin
      username: minsu
      password: minsu
      host: localhost
      port: 27017
      database: handySub
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true


logging:
  level:
    org:
      hibernate.SQL: debug
      hibernate.type: trace
server:
  port: 8080