spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true


logging:
  level:
    org:
      hibernate.SQL: debug
      hibernate.type: trace
server:
  port: 8080
